const ICONS: Record<string, string> = {
  'audio':                      '♪',
  'audio-amplifier':            '♪',
  'audio-turntable':            '◉',
  'audio-headphones':           '◉',
  'audio-speaker':              '♪',
  'laptops':                    '□',
  'laptop-windows':             '□',
  'laptop-macbook-pro':         '□',
  'laptop-macbook-air':         '□',
  'laptop-chromebook':          '□',
  'laptop-ram':                 '≡',
  'laptop-ssd':                 '▬',
  'laptop-charger':             '⚡',
  'desktop':                    '▣',
  'desktop-imac':               '▣',
  'desktop-cpu':                '⚡',
  'desktop-gpu':                '⚡',
  'desktop-psu':                '⚡',
  'desktop-motherboard':        '⊟',
  'desktop-storage':            '▬',
  'consoles':                   '▷',
  'console-playstation':        '▷',
  'console-xbox':               '▷',
  'console-nintendo-home':      '▷',
  'console-nintendo-portable':  '▷',
  'console-controller':         '▷',
  'mobile':                     '|',
  'mobile-iphone':              '|',
  'mobile-android-flagship':    '|',
  'mobile-android-mid':         '|',
  'mobile-ipad':                '|',
  'mobile-android-tablet':      '|',
  'peripherals':                '⊞',
  'peripheral-monitor':         '⊞',
  'peripheral-keyboard':        '⊞',
  'peripheral-mouse':           '⊞',
  'peripheral-webcam':          '⊞',
  'consumables':                '+',
  'consumable-solder':          '+',
  'consumable-flux':            '+',
  'consumable-thermal':         '+',
  'tools':                      '⚙',
  'tool-multimeter':            '⚙',
  'tool-oscilloscope':          '⚙',
  'tool-soldering':             '⚙',
  'tool-printer':               '⚙',
  'lots-category':              '□',
  'generic':                    '·',
  'generic-part':               '·',
}

export function getCategoryIcon(slug: string): string {
  return ICONS[slug] ?? ICONS[slug.split('-')[0]] ?? '·'
}
